import type { FloatingContent, Props, PropsNoRender } from '$lib/internals/types.js';

//
// ~ROOT
//
export interface MenuProps<S = any> extends PropsNoRender<S>, FloatingContent {}

//
// ~TRIGGER
//
export interface MenuTriggerProps<P = any, S = any> extends Props<HTMLButtonElement, P, S> {}

//
// ~CONTENT
//
export interface MenuContentProps<P = any, S = any> extends Props<HTMLElement, P, S> {}

//
// ~ARROW
//
export interface MenuArrowProps<P = any, S = any> extends Props<HTMLElement, P, S> {}

//
// ~ITEM
//
export interface MenuItemProps<P = any, S = any> extends Props<HTMLElement, P, S> {
	/**
	 * Turns the item into an anchor tag with the provided `href` applied.
	 */
	href?: string;
	/**
	 * Disables the item, skipping mouse/keyboard navigation and stopping events from firing.
	 *
	 * ### `$bindable`
	 */
	disabled?: boolean;
	/**
	 * Closes the item on click/keyboard press.
	 */
	closeOnClick?: boolean;
}

//
// ~SUB
//
export interface MenuSubProps<S = any> extends PropsNoRender<S>, FloatingContent {
	/**
	 * The unique ID of the sub menu.
	 *
	 * This ID must not change on renders. So using an autogenerated id will not work and cause the\
	 * sub menus to fail.
	 */
	name: string;
}

//
// ~SUB TRIGGER
//
export interface MenuSubTriggerProps<P = any, S = any> extends Props<HTMLButtonElement, P, S> {}

//
// ~CONTENT
//
export interface MenuSubContentProps<P = any, S = any> extends Props<HTMLElement, P, S> {}
