import type { FloatingContent, Props, PropsNoRender } from '$lib/internals/types.js';

//
// ~ROOT
//
export interface MenuProps extends PropsNoRender<MenuState>, FloatingContent {}
export interface MenuState {
	/**
	 * True if the contents are visible.
	 */
	visible: boolean;
}

//
// ~TRIGGER
//
export interface MenuTriggerProps<P = any> extends Props<HTMLButtonElement, P, MenuTriggerState> {}
export interface MenuTriggerState {
	/**
	 * True if the contents are visible.
	 */
	visible: boolean;
}

//
// ~CONTENT
//
export interface MenuContentProps<P = any> extends Props<HTMLElement, P, MenuContentState> {}
export interface MenuContentState {
	/**
	 * True if the contents are visible.
	 */
	visible: boolean;
}

//
// ~ARROW
//
export interface MenuArrowProps<P = any> extends Props<HTMLElement, P, MenuArrowState> {}
export interface MenuArrowState {
	/**
	 * True if the contents are visible.
	 */
	visible: boolean;
}

//
// ~ITEM
//
export interface MenuItemProps<P = any> extends Props<HTMLElement, P, MenuItemState> {
	/**
	 * Turns the item into an anchor tag with the provided `href` applied.
	 */
	href?: string;
	/**
	 * Disables the item, skipping mouse/keyboard navigation and stopping events from firing.
	 *
	 * ### `$bindable`
	 */
	disabled?: boolean;
	/**
	 * Closes the item on click/keyboard press.
	 */
	closeOnClick?: boolean;
}
export interface MenuItemState {
	/**
	 * True if the item is disabled.
	 */
	disabled: boolean;
	/**
	 * True if the item is being hovered.
	 */
	active: boolean;
}

//
// ~SUB
//
export interface MenuSubProps extends PropsNoRender<MenuSubState>, FloatingContent {
	/**
	 * The unique ID of the sub menu.
	 *
	 * This ID must not change on renders. So using an autogenerated id will not work and cause the sub menus to fail.
	 */
	name: string;
}
export interface MenuSubState {
	/**
	 * True if the contents are visible.
	 */
	visible: boolean;
}

//
// ~SUB TRIGGER
//
export interface MenuSubTriggerProps<P = any> extends Props<HTMLButtonElement, P, MenuSubTriggerState> {}
export interface MenuSubTriggerState {
	/**
	 * True if the sub menu is disabled.
	 */
	disabled: boolean;
	/**
	 * True if item is hovered.
	 */
	active: boolean;
	/**
	 * True if the sub menu is opened.
	 */
	opened: boolean;
}

//
// ~CONTENT
//
export interface MenuSubContentProps<P = any> extends Props<HTMLElement, P, MenuSubContentState> {}
export interface MenuSubContentState {
	/**
	 * True if the contents are visible.
	 */
	visible: boolean;
}
